definitions:
  models.PaymentResponse:
    properties:
      amount:
        type: integer
      currency:
        type: string
      customer:
        properties:
          email:
            type: string
          name:
            type: string
        type: object
      expireTime:
        type: string
      notes:
        properties:
          classBooked:
            type: string
          dateOfBooking:
            type: string
          trainId:
            type: string
          user_id:
            type: string
        type: object
      paymentLink:
        type: string
    type: object
host: localhost:8082
info:
  contact:
    email: swiggyb2013@datascience.manipal.edu
    name: API Support
    url: http://www.swagger.io/support
  description: Swagger Train-Ticket Booking System API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Train-Ticket Booking System API
  version: "1.0"
paths:
  /payment/pay:
    post:
      consumes:
      - application/json
      description: Get razorpay payment link along with user details for ticket
      parameters:
      - description: date of Booking
        in: body
        name: Date
        required: true
        schema:
          type: string
      - description: amount of tickets
        in: body
        name: Amount
        required: true
        schema:
          type: integer
      - description: type of currency in which transaction will happend
        in: body
        name: Currency
        required: true
        schema:
          type: string
      - description: train number
        in: body
        name: TrainID
        required: true
        schema:
          type: string
      - description: reference id is a unique id for payment gatway
        in: body
        name: ReferenceID
        schema:
          type: string
      - description: to which class the tickets belongs, e.g, SL, AC-1, AC-2, etc
        in: body
        name: ClassBooking
        required: true
        schema:
          type: string
      - description: user name
        in: body
        name: Name
        required: true
        schema:
          type: string
      - description: user email id
        in: body
        name: Email
        required: true
        schema:
          type: string
      - description: user unique id
        in: body
        name: User_id
        required: true
        schema:
          type: string
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PaymentResponse'
        "400":
          description: Bad Request
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      summary: Pay for train ticket
      tags:
      - payment
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
